### ISSUE TITLE
User Management (Login, Registration)

### ISSUE THREAD

**Issue by ZenaguiAnas** [sohaibMan/bricoll#3]
# **User Management** 

## 📌 Target
In the registration operation, the user can make a registration and choose the profile type either as freelancer or as client, the first one (freelancer) if he is looking for work, and client if he want to make a hiring for a project, in for each profile type the registration will be passing to multi-steps.

[Step 1: Sign up using the email address, or OAuth API (Google, Facebook, Apple) Account
](url)[Step 2: Choosing the profile type](url)
[Step 3: Adding the personal information](url)
[Step 4: Verify your email to proceed](url)
[Step 5: Become a freelancer or client on Upwork](url)
[Step 6: Login as freelancer or as client on Upwork](url)

## 💡 Rules
-> The user choose the profile type then making a registration either with OAuth or manually.
-> The user adds his personal information (firstName, lastName, password, location)
-> Inserting some information related to the work we do (A photo of himself, his title, his overview, his Work history, At least one skill up to 15 skills)
-> The user highlights the educational information
-> Highlights the past work experience
-> Adding the language proficiency
-> Set his hourly rate
-> Add the contact details

## ✅ TODOS

- [x]  Handling the signup operation for user, by implementing mutation function `signup()`
- [x]  Handling the login operation for user, by implementing mutation function `login()`
- [x]  Handling the profile editing operation for user, by implementing mutation function `updateProfile()`
- [x]  Handling the password updating operation for user, by implementing mutation function `updatePassword()`
- [x]  Handling the profile deleting operation for user, by implementing mutation function `deleteProfile()`
- [x]  Implementing query function `getUser()`
- [x]  Implementing query function `logout()`
- [x]  Implementing a function to generate the token using JWT (JSON Web Tokens) `generateToken()`
- [x]  Implementing a function to send the token `sendingToken()`
- [x]  Handling the forget password operation, by implementing mutation function `forgetPassword()`
- [x]  Handling the reset password operation, by implementing mutation function `resetPassword()`

@sohaibMan what do you think about these key features ?
